## CUSTOMERS TABLE CREATION
CREATE TABLE CUSTOMERS(
  customer_id NUMBER PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  region VARCHAR(100) NOT NULL
);

 ## PRODUCT TABLE CREATION
CREATE TABLE PRODUCT(
   product_id NUMBER PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   price NUMBER(10,2),
   category VARCHAR(100) 
);

## TRANSACTIONS TABLE CREATION
CREATE TABLE TRANSACTIONS(
  transaction_id NUMBER PRIMARY KEY,
  customer_id NUMBER,
  product_id NUMBER,
  amount NUMBER(10,2),
  quantity NUMBER,
  sale_date DATE
);

## BELOW ARE THE SAMPLE RECORDS INSERTED
--- CUSTOMERS
INSERT INTO CUSTOMERS VALUES (001, 'Aline Von', 'Nyarugenge');
INSERT INTO CUSTOMERS VALUES (002, 'Keith Powers', 'Musanze');
INSERT INTO CUSTOMERS VALUES (003, 'Meghan Lowel', 'Nyamagabe');
INSERT INTO CUSTOMERS VALUES (004, 'Alex Volkov', 'Gasabo');
INSERT INTO CUSTOMERS VALUES (005, 'Stella Alonso', 'Nyarugenge');
--- PRODUCTS
INSERT INTO PRODUCTS VALUES (101, 'Red velvet', 30000, 'Cake');
INSERT INTO PRODUCTS VALUES (102, 'chocolate, 15000, 'Cake');
INSERT INTO PRODUCTS VALUES (103, 'muffin', 1500, 'Bread');
  
  
  
  
  
